from decouple import config

TOKEN = config('OPCODE_TOKEN')
VERIFICATION_TOKEN = config('OPCODE_VERIFICATION_TOKEN')
COMMUNITY_CHANNEL = config('OPCODE_COMMUNITY_ID')
MENTORS_INTERNAL_CHANNEL = config('OPCODE_MENTORS_INTERNAL_CHANNEL')

AIRTABLE_BASE_KEY = config('OPCODE_AIRTABLE_BASE_KEY')
AIRTABLE_API_KEY = config('OPCODE_AIRTABLE_TOKEN')

# DB_USERNAME = config('PROD_DB_USERNAME')
# DB_PASSWORD = config('PROD_DB_PASSWORD')
# DB_DIALECT = config('PROD_DB_DIALECT')
# DB_ADDR = config('PROD_DB_ADDR')
# DB_NAME = config('PROD_DB_NAME')
DATABASE_URI = config('PROD_DATABASE_URI')

RECAPTCHA_SECRET = config('RECAPTCHA_SECRET')
GITHUB_JWT = config('GITHUB_JWT')
GITHUB_REPO_PATH = config('GITHUB_REPO_PATH')